name: qSoBaa

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Agrega RDG code'
        required: true
      pincode:
        description: 'Pin de 6 digitos'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Descargando Dw_Script
      run: powershell -File dw_script.ps1
    - name: Iniciando Globo
      run: ./globo.ps1
    - name: Iniciando qSoBaa 
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Mandando pulsaciones de corazon
      run: ./lop.ps1
