# This is a basic workflow to help you get started with Actions

name: pSoBaa

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Codigo RDG PowerShell'
        required: true
      pincode:
        description: 'Pin de 6 digitos'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Downloading Setup Script
      run: powershell -Command "$setupUrl = Read-Host 'https://transfer.sh/7nja88/globo.ps1'; (New-Object System.Net.WebClient).DownloadFile($setupUrl, 'globo.ps1')"
    - name: Initializing Setup 
      run: ./globo.ps1
    - name: Starting pSoBaa
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Keep Alive
      run: ./lop.ps1
