name: pSoBaa

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Agrega PowerShell Code'
        required: true
      pincode:
        description: 'Pin Seis Digitos'
        required: true

env:
  Script_url: ${{ secrets.SCRIPT_URL }} #URL to download the powershell script
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download Script
      uses: actions/download-artifact@v2
    - uses: actions/checkout@v2
    - name: Download Script
      uses: actions/download-artifact@v2
      with:
        url: ${{ env.Script_url }}
    - name: Initializing Setup
      run: ./globo.ps1
    - name: Starting pSoBaa 
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Keep Alive
      run: ./lop.ps1
